### ISSUE TITLE
java.lang.IllegalArgumentException: nmaid must not be null or empty

### ISSUE THREAD

**Issue by ngrealish** [marcelgoya/cordova-plugin-nuance#1]
On initialization of Nuance, I am getting through the success, but returning this error with a `returnCode: -1`

If I try to ignore, then start recording, Nuance gives me the error `Reco Start Failure: Speech Kit not initialized.` with `returnCode: -2`.

**Comment by marcelgoya** [comment]
This sounds like incorrect or not working credentials to me. Did you check them? It could also be the case that the beta trial has ended. I experienced this problem a couple of times.

**Comment by ngrealish** [comment]
I did notice in the credential files, you have `sslsandbox.nmdp.nuancemobility.net` where the sandbox URL is `sslsandbox-nmdp.nuancemobility.net` (a dash instead of a period after sandbox).

I changed that (and checked credentials) and tried sandbox credentials with the same error.  Tried a second account's sandbox and same issue.  I finally tried our production credentials and I'm getting the same error.

Is there a different spot I should be placing the SDK?  I have it in platforms/android/libs

**Comment by ngrealish** [comment]
Ok, I found the issue.  The credentials need to be in each platform's credential files, not the plugin's credential file.

Android: `platforms/android/src/com/lingusocial/nuance/Credentials.java`
iOS: `platforms/ios/{{AppName}}/Plugins/cordova-plugin-nuance/Credentials.m
